Use osx-universal ldc2 builds on macOS
dlang-community/setup-dlang pull request #59
Opened 2022-09-12 15:22 UTC by LunaTheFoxgirl

This is necessary to build universal macOS binaries.

2022-09-12 15:39 UTC, LunaTheFoxgirl commented
I recommend doing a squash and merge on this. additionally there should probably be added a check to ensure that older versions of LDC2 still just use the x86_64 version

2022-09-12 16:32 UTC, LunaTheFoxgirl commented on src/compiler.ts
> +            libpath: [ `/ldc2-${version}-osx-universal/lib-arm64`, `/ldc2-${version}-osx-universal/lib-x86_64` ],
Just making sure that we can link to both arm64 and x86_64 phobos which is necessary. Otherwise compilation will fail when making universal binaries.

2022-09-12 16:33 UTC, WebFreak001 commented on src/compiler.ts
> +            libpath: [ `/ldc2-${version}-osx-universal/lib-arm64`, `/ldc2-${version}-osx-universal/lib-x86_64` ],
no I mean before this change there was `lib64` here, but that didn't correspond to a folder in the release archive, where do these paths come from?

2022-09-12 16:34 UTC, LunaTheFoxgirl commented on src/compiler.ts
> +            libpath: [ `/ldc2-${version}-osx-universal/lib-arm64`, `/ldc2-${version}-osx-universal/lib-x86_64` ],
I am not sure, I just followed whatever standard seemed to be there tbh. I know on my local m1 mac I had to add those folders to the PATH otherwise linking would fail.

2022-09-12 16:38 UTC, WebFreak001 requested changes

2022-09-12 16:38 UTC, WebFreak001 commented on src/compiler.ts
> +        case "darwin": suffix = 'osx-universal'; ext = 'tar.xz'; break;
`universal` is only released since [LDC 1.30.0-beta1](https://github.com/ldc-developers/ldc/releases/tag/v1.30.0-beta1), need to add a check here if it's at least this old

2022-09-12 16:39 UTC, LunaTheFoxgirl commented on src/compiler.ts
> +        case "darwin": suffix = 'osx-universal'; ext = 'tar.xz'; break;
This is here where I admit that I haven't written js in years

2022-09-12 16:41 UTC, WebFreak001 commented on src/compiler.ts
> +        case "darwin": suffix = 'osx-universal'; ext = 'tar.xz'; break;
actually nevermind, this is for fetching master

2022-09-12 16:41 UTC, LunaTheFoxgirl commented on src/compiler.ts
> +        case "darwin": suffix = 'osx-universal'; ext = 'tar.xz'; break;
This is for resolving master branch, no? in which case wouldn't it always chose the newest available version?
I don't see any obvious place to get a specific version from

2022-09-12 16:45 UTC, WebFreak001 commented on src/compiler.ts
> +            url: `${base_url}-osx-universal.tar.xz`,
ok so on this branch we should only return the object describing universal releases since version [LDC 1.30.0-beta1](https://github.com/ldc-developers/ldc/releases/tag/v1.30.0-beta1)

2022-09-12 23:02 UTC, WebFreak001 approved these changes

2022-09-12 23:03 UTC, WebFreak001 commented
@Geod24 can you review as well? I modified the PR a bit to

1) fixed lib paths on posix (even if they aren't currently used)
2) added basic semver parsing code (just reused the code from code-d, it's pretty simple code)
3) added conditional properties based on ldc version

2022-09-18 17:43 UTC, WebFreak001 commented
will merge soon if no objections

2022-10-15 00:30 UTC, WebFreak001 commented
sorry, forgot about this - rebased and gonna merge once CI is green

2022-10-15 00:41 UTC, merged